// Independent copy for the spatial variant. These are development goals;
// the exhibition models are illustrations, not simulation results.
export const chapters = [
  {
    id: "introduction",
    label: "The possibility",
    short: "Start",
    title: "Every great design\nstarts with a question.",
    body: "What if physical simulation could keep pace with your ideas? We are building a new CFD engine to help make that possible.",
    link: "Discover Nabla",
    href: "#perspective",
    image: "boeing",
    note: "A new perspective on CFD",
  },
  {
    id: "aerospace",
    label: "Aerospace",
    short: "Air",
    title: "Give better ideas\nroom to fly.",
    body: "From a wing to its wake, flow shapes performance. Our goal is to give engineers more useful physical feedback, with less preparation.",
    link: "Explore applications",
    href: "/industries",
    image: "boeing",
    note: "Boeing 747 · Aerodynamics",
  },
  {
    id: "marine",
    label: "Marine",
    short: "Water",
    title: "Look beneath\nthe surface.",
    body: "Hulls, propellers and the water around them form one connected problem. We aim to make these demanding flows easier to explore in detail.",
    link: "Explore applications",
    href: "/industries",
    image: "cargo-ship",
    note: "Cargo ship · Hydrodynamics",
  },
  {
    id: "mobility",
    label: "Motorsport",
    short: "Motion",
    title: "Find the shape\nof what comes next.",
    body: "Aerodynamics and thermal management influence every vehicle. Faster physical feedback could help engineers compare more design possibilities.",
    link: "Explore applications",
    href: "/industries",
    image: "formula-one",
    note: "Formula racing · Aerodynamics",
  },
  {
    id: "cooling",
    label: "Data centre cooling",
    short: "Energy",
    title: "Follow the flow.\nUnderstand the heat.",
    body: "The digital world depends on physical infrastructure. We are exploring how fluid simulation could support the design of more effective cooling systems.",
    link: "Discover our approach",
    href: "#perspective",
    image: "industrial",
    note: "Fluid systems · Heat transfer",
  },
  {
    id: "engineering",
    label: "Back to the engineer",
    short: "People",
    title: "Great ideas need\nphysical answers.",
    body: "AI can generate a new design in moments. Each candidate still needs physical validation. We are building Nabla to help engineers close that gap.",
    link: "Start a conversation",
    href: "/contact",
    image: "turbomachinery",
    note: "Human ambition · Physical understanding",
  },
] as const;
